blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    # url(r'^$', a, name='a'),
    url(r'^blog/$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^article/$', views.article, name='article'),
    url(r'^comment/post/$', views.comment_post, name='comment_post'),
    url(r'^logout$', views.do_logout, name='logout'),
    url(r'^reg', views.do_reg, name='reg'),
    url(r'^login', views.do_login, name='login'),
    url(r'^category/$', views.category, name='category'),
    url(r'^a', views.a, name='a'),
    # url(r'^test', views.test, name='test'),
    # url(r"^about", views.about, name="about"),
]

blog_project/urls.py
from django.views.generic.base import RedirectView
from django.views.static import serve
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from blog.upload import upload_image
from blog.views import about
from resume import views
from demo.views import demo, test_ajax, trex, trexUpload ,trexRank
from tool.views import img2base64, img2base64_upload
# from demo.views import
urlpatterns = [
    url(r'^favicon.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
    url(r"^uploads/(?P<path>.*)$", \
                serve, \
                {"document_root": settings.MEDIA_ROOT,}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r'^admin', include(admin.site.urls)),
    # 简历
    url(r'^resume/', views.resume,name="简历"),
    url(r'^resume_mobile/', views.resume_mobile,name="手机简历"),
    url(r'^resume_pc/', views.resume_pc,name="手机简历"),
    url(r'^m', views.phone,name="移动端简历"),

    url(r"^demo/(?P<name>[^/]+)/$", demo),
    url(r"^demo/(?P<name>ife/[^/]+)/$", demo),
    url(r"^about", about),
    url(r'^$', views.resume,name="简历"),
    # demo 分发
    url(r'^', include('blog.urls')),
    url(r'^test',test_ajax, name='test'),
    # url(r'^test',"demo.views.test", name='test'),
#     文件下载
#     url(r"^download/(?P<name>[^/]+)$", "demo.views.file_download", name="下载"),

    url(r"tool/$",img2base64),
    url(r"tool/img2base64/$",img2base64_upload),
    # url(r"tool/(?P<url>.*)","tool.views.img2base")

#     小恐龙trex
    url(r"^trex/$",trex),
    url(r"trex/uploadStorage/$",trexUpload),
    url(r"trex/rank/$",trexRank)


]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# 用户模型.
# 第一种：采用的继承方式扩展用户信息（本系统采用）
# 扩展：关联的方式去扩展用户信息
class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

# tag（标签）
class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 分类
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(default=999,verbose_name='分类的排序')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __str__(self):
        return self.name

# 自定义一个文章Model的管理器
# 1、新加一个数据处理的方法
# 2、改变原有的queryset
class ArticleManager(models.Manager):
    def distinct_date(self):
        distinct_date_list = []
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y/%m')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list

# 文章模型
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=50, blank=True, null=True, verbose_name='文章描述' )
    content = models.TextField(verbose_name='文章内容')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User,blank=True, null=True, verbose_name='用户')
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='分类')
    tag = models.ManyToManyField(Tag,blank=True, null=True, verbose_name='标签')

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return self.title

# 评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    username = models.CharField(max_length=30, blank=True, null=True, verbose_name='用户名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户')
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章')
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.id)

# 友情链接
class Links(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    description = models.CharField(max_length=200, verbose_name='友情链接描述')
    callback_url = models.URLField(verbose_name='url地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

# 广告
class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='广告标题')
    description = models.CharField(max_length=200,  verbose_name='广告描述')
    image_url = models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径')
    callback_url = models.URLField(null=True, blank=True, verbose_name='回调url')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = u'广告'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
import logging
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
from django.db import connection
from django.db.models import Count
from blog.models import *
from blog.forms import *
import json

logger = logging.getLogger('blog.views')

def a(request):
    article_list = Article.objects.all()
    article_list = getPage(request, article_list)
    return render(request,'blog/blog.html',locals())


# 测试
# def test(request):
#     # article_list = Article.objects.all()
#     # article_list = getPage(request, article_list)
#     return render(request,"blog/blog_test.html",locals())


def about(request):
    return render(request,"blog/about.html")


# Create your views here.
def global_setting(request):
    # 站点基本信息
    SITE_URL = settings.SITE_URL
    SITE_NAME = settings.SITE_NAME
    SITE_DESC = settings.SITE_DESC
    # 分类信息获取（导航数据）
    category_list = Category.objects.all()[:6]
    # 文章归档数据
    archive_list = Article.objects.distinct_date()
    # 广告数据（同学们自己完成）
    # 标签云数据（同学们自己完成）
    # 友情链接数据（同学们自己完成）
    # 文章排行榜数据（按浏览量和站长推荐的功能同学们自己完成）
    # 评论排行
    comment_count_list = Comment.objects.values('article').annotate(comment_count=Count('article')).order_by('-comment_count')
    article_comment_list = [Article.objects.get(pk=comment['article']) for comment in comment_count_list]
    return locals()

def index(request):
    try:
        # 最新文章数据
        article_list = Article.objects.all()
        article_list = getPage(request, article_list)
        # 文章归档
        # 1、先要去获取到文章中有的 年份-月份  2015/06文章归档
        # 使用values和distinct去掉重复数据（不可行）
        # print Article.objects.values('date_publish').distinct()
        # 直接执行原生sql呢？
        # 第一种方式（不可行）
        # archive_list =Article.objects.raw('SELECT id, DATE_FORMAT(date_publish, "%%Y-%%m") as col_date FROM blog_article ORDER BY date_publish')
        # for archive in archive_list:
        #     print archive
        # 第二种方式（不推荐）
        # cursor = connection.cursor()
        # cursor.execute("SELECT DISTINCT DATE_FORMAT(date_publish, '%Y-%m') as col_date FROM blog_article ORDER BY date_publish")
        # row = cursor.fetchall()
        # print row
    except Exception as e:
        print (e)
        logger.error(e)
    # return render(request, 'index.html', locals())
    return render(request, 'blog/blog.html', locals())

def archive(request):
    try:
        # 先获取客户端提交的信息
        year = request.GET.get('year', None)
        month = request.GET.get('month', None)
        article_list = Article.objects.filter(date_publish__icontains=year+'-'+month)
        article_list = getPage(request, article_list)
    except Exception as e:
        logger.error(e)
    return render(request, 'archive.html', locals())

# 按标签查询对应的文章列表
def tag(request):
    try:
        # 同学们自己实现该功能
        pass
    except Exception as e:
        logger.error(e)
    return render(request, 'archive.html', locals())

# 分页代码
def getPage(request, article_list):
    paginator = Paginator(article_list, 10)
    try:
        page = int(request.GET.get('page', 1))
        article_list = paginator.page(page)
    except (EmptyPage, InvalidPage, PageNotAnInteger):
        article_list = paginator.page(1)
    return article_list

# 文章详情
def article(request):
    try:
        # 获取文章id
        id = request.GET.get('id', None)
        try:
            # 获取文章信息
            article = Article.objects.get(pk=id)
        except Article.DoesNotExist:
            return render(request, 'failure.html', {'reason': '没有找到对应的文章'})

        # 评论表单
        comment_form = CommentForm({'author': request.user.username,
                                    'email': request.user.email,
                                    'url': request.user.url,
                                    'article': id} if request.user.is_authenticated() else{'article': id})
        # 获取评论信息
        comments = Comment.objects.filter(article=article).order_by('id')
        comment_list = []
        for comment in comments:
            for item in comment_list:
                if not hasattr(item, 'children_comment'):
                    setattr(item, 'children_comment', [])
                if comment.pid == item:
                    item.children_comment.append(comment)
                    break
            if comment.pid is None:
                comment_list.append(comment)
    except Exception as e:
        print (e)
        logger.error(e)
    return render(request, 'blog/article.html', locals())

# 提交评论
def comment_post(request):
    try:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            #获取表单信息
            comment = Comment.objects.create(username=comment_form.cleaned_data["author"],
                                             email=comment_form.cleaned_data["email"],
                                             url=comment_form.cleaned_data["url"],
                                             content=comment_form.cleaned_data["comment"],
                                             article_id=comment_form.cleaned_data["article"],
                                             user=request.user if request.user.is_authenticated() else None)
            comment.save()
        else:
            return render(request, 'failure.html', {'reason': comment_form.errors})
    except Exception as e:
        logger.error(e)
    return redirect(request.META['HTTP_REFERER'])

# 注销
def do_logout(request):
    try:
        logout(request)
    except Exception as e:
        print (e)
        logger.error(e)
    return redirect(request.META['HTTP_REFERER'])

# 注册
def do_reg(request):
    try:
        if request.method == 'POST':
            reg_form = RegForm(request.POST)
            if reg_form.is_valid():
                # 注册
                user = User.objects.create(username=reg_form.cleaned_data["username"],
                                    email=reg_form.cleaned_data["email"],
                                    url=reg_form.cleaned_data["url"],
                                    password=make_password(reg_form.cleaned_data["password"]),)
                user.save()

                # 登录
                user.backend = 'django.contrib.auth.backends.ModelBackend' # 指定默认的登录验证方式
                login(request, user)
                return redirect(request.POST.get('source_url'))
            else:
                return render(request, 'failure.html', {'reason': reg_form.errors})
        else:
            reg_form = RegForm()
    except Exception as e:
        logger.error(e)
    return render(request, 'reg.html', locals())

# 登录
def do_login(request):
    try:
        if request.method == 'POST':
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                # 登录
                username = login_form.cleaned_data["username"]
                password = login_form.cleaned_data["password"]
                user = authenticate(username=username, password=password)
                if user is not None:
                    user.backend = 'django.contrib.auth.backends.ModelBackend' # 指定默认的登录验证方式
                    login(request, user)
                else:
                    return render(request, 'failure.html', {'reason': '登录验证失败'})
                return redirect(request.POST.get('source_url'))
            else:
                return render(request, 'failure.html', {'reason': login_form.errors})
        else:
            login_form = LoginForm()
    except Exception as e:
        logger.error(e)
    return render(request, 'login.html', locals())

def category(request):
    try:
        # 先获取客户端提交的信息
        cid = request.GET.get('cid', None)
        try:
            category = Category.objects.get(pk=cid)
        except Category.DoesNotExist:
            return render(request, 'failure.html', {'reason': '分类不存在'})
        article_list = Article.objects.filter(category=category)
        article_list = getPage(request, article_list)
    except Exception as e:
        logger.error(e)
    # return render(request, 'blog/category.html', locals())
    return render(request, 'blog/blog.html', locals())

templates/blog/ad.html
{% load staticfiles %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner"> <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" /></a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

  slider.data= [
    {
        "id":"slide-img-1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },
    {
        "id":"slide-img-2",
        "client":"标题2",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-3",
        "client":"标题3",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-4",
        "client":"标题4",
        "desc":"add your description here"
    }
  ];

    </script>
    </div>
    <!-- banner代码 结束 -->

templates/blog/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ request.GET.year }}/{{ request.GET.month }}文章归档</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/blog/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load myfilter %}
{% block left_content %}
    <div class="postdate">
      <div class="month">{{ article.date_publish | month_to_upper }}</div>
      <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
          {{ article.content | safe }}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <div class="info">
        Address:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>

      <div class="commentstitle"><h3 id="comments"><span class="commentsnumber">only 1 comment</span> untill now</h3></div>

      <ol class="commentlist">
          {% for comment in comment_list %}
          <li id="comment-59418">
                <div class="top"><a href='{{ comment.url }}' rel='external nofollow' class='url'>{{ comment.username }}</a><span class="time"> @ <a href="#comment-59418" title="">{{ comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                <div><img alt='' src='{% static 'images/default.jpg' %}' class='avatar avatar-32 photo' height='32' width='32' /></div>

                <div class="body">
                                <p>{{ comment.content }}</p>
                </div>
          </li>
          {% for children_comment in comment.children_comment %}
          <li id="comment-59542">
                <div class="reply">
                  <div class="top"><a href="{{ children_comment.url }}" rel="external nofollow" class="url">{{ children_comment.username }}</a><span class="time"> @ <a href="#comment-59543" title="">{{ children_comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                  <div><img alt="" src="{% static 'images/default.jpg' %}" class="avatar avatar-32 photo" height="32" width="32"></div>

                  <div class="body">
                                        {{ children_comment.content }}                  </div>
                </div>
          </li>
          {% endfor %}
          {% endfor %}
      </ol>

    <div id="commentform">
    <h3 id="respond">Add your comment now</h3>
    {% if not request.user.is_authenticated %}
    <div class='login_info'>还没有登陆？可以登录后再评论哦。<b><a href="{% url 'login' %}">&raquo;去登录</a>&nbsp;<a href="{% url 'reg' %}">&raquo;去注册</a></b></div>
    {% else %}
    <div class='login_info'><b>{{ request.user.username }}</b>,快来写点评论吧!&nbsp;<a href="{% url 'logout' %}">注销</a></div>
    {% endif %}
    <form action="{% url 'comment_post' %}" method="post">
    {% csrf_token %}
    <p>{{ comment_form.author }}
    <label for="author">Name (required)</label></p>

    <p>{{ comment_form.email }}
    <label for="email">Email (Will NOT be published) (required)</label></p>

    <p>{{ comment_form.url }}
    <label for="url">URL</label></p>


    <!--<p><small><strong>XHTML:</strong> You can use these tags: &lt;a href=&quot;&quot; title=&quot;&quot;&gt; &lt;abbr title=&quot;&quot;&gt; &lt;acronym title=&quot;&quot;&gt; &lt;b&gt; &lt;blockquote cite=&quot;&quot;&gt; &lt;cite&gt; &lt;code class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;del datetime=&quot;&quot;&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=&quot;&quot;&gt; &lt;strike&gt; &lt;strong&gt; &lt;pre class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;span class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; </small></p>-->

    <p>{{ comment_form.comment }}</p>

    <p>
        {{ comment_form.article }}
        <input name="submit" type="submit" id="submit" tabindex="5" value="Submit" class="button" />
    </p>
    </form>
    </div>
{% endblock %}

templates/blog/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ category.name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/blog/failure.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作失败</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
    <style type="text/css">
        ul li{float: left; margin-left: 10px;}
    </style>
</head>

<body>
<div class="microoh-main" style="height: 150px">
    <div class="container" style="position: absolute; top: 20px; left: 20px;">
        <div style="height: 150px">
            <i class="v5-icon v5-icon-wrong"></i>
            <span>{{ reason | safe }}</span>
        </div>
    </div>
</div>
</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>最新文章</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/blog/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
			<form action="{% url 'login' %}" method="post">
                {% csrf_token %}
				<ul class="right-form">
					<h2>Login:</h2>
					<li><input type="text" name="username" placeholder="Username" required/></li>
					<li><input type="password" name="password" placeholder="Password" required/></li>
					<input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
                    <input type="submit" value="Login" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>

			</form>
	</div>
</body>
</html>

templates/blog/pagination.html
<div id="pagination">
    <ul id="pagination-flickr">
    {% if article_list.has_previous %}
    <li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}
     <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
    {% if article_list.has_next %}
      <li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

templates/blog/success.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作成功</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
</head>

<body>
<div class="microoh-main" style="height: 100px">
    <div style="position: absolute; top: 20px; left: 20px;">
            <i class="v5-icon v5-icon-right"></i>
            <span>{{ reason | safe }}</span>
    </div>
</div>
</body>
</html>